
package com.brickset.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-28T18:10:42.179-04:00
 * Generated source version: 3.0.4
 * 
 */
public final class BricksetAPIv2Soap_BricksetAPIv2Soap_Client {

    private static final QName SERVICE_NAME = new QName("http://brickset.com/api/", "BricksetAPIv2");

    private BricksetAPIv2Soap_BricksetAPIv2Soap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BricksetAPIv2.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BricksetAPIv2 ss = new BricksetAPIv2(wsdlURL, SERVICE_NAME);
        BricksetAPIv2Soap port = ss.getBricksetAPIv2Soap();  
        
        {
        System.out.println("Invoking setCollection...");
        java.lang.String _setCollection_apiKey = "";
        java.lang.String _setCollection_userHash = "";
        int _setCollection_setID = 0;
        int _setCollection_qtyOwned = 0;
        int _setCollection_wanted = 0;
        java.lang.String _setCollection__return = port.setCollection(_setCollection_apiKey, _setCollection_userHash, _setCollection_setID, _setCollection_qtyOwned, _setCollection_wanted);
        System.out.println("setCollection.result=" + _setCollection__return);


        }
        {
        System.out.println("Invoking setCollectionWants...");
        java.lang.String _setCollectionWants_apiKey = "";
        java.lang.String _setCollectionWants_userHash = "";
        int _setCollectionWants_setID = 0;
        int _setCollectionWants_wanted = 0;
        java.lang.String _setCollectionWants__return = port.setCollectionWants(_setCollectionWants_apiKey, _setCollectionWants_userHash, _setCollectionWants_setID, _setCollectionWants_wanted);
        System.out.println("setCollectionWants.result=" + _setCollectionWants__return);


        }
        {
        System.out.println("Invoking getReviews...");
        java.lang.String _getReviews_apiKey = "";
        int _getReviews_setID = 0;
        com.brickset.api.ArrayOfReviews _getReviews__return = port.getReviews(_getReviews_apiKey, _getReviews_setID);
        System.out.println("getReviews.result=" + _getReviews__return);


        }
        {
        System.out.println("Invoking getCollectionDetail...");
        java.lang.String _getCollectionDetail_apiKey = "";
        java.lang.String _getCollectionDetail_userHash = "";
        java.lang.String _getCollectionDetail_setID = "";
        com.brickset.api.ArrayOfCollectionDetails _getCollectionDetail__return = port.getCollectionDetail(_getCollectionDetail_apiKey, _getCollectionDetail_userHash, _getCollectionDetail_setID);
        System.out.println("getCollectionDetail.result=" + _getCollectionDetail__return);


        }
        {
        System.out.println("Invoking getRecentlyUpdatedSets...");
        java.lang.String _getRecentlyUpdatedSets_apiKey = "";
        int _getRecentlyUpdatedSets_minutesAgo = 0;
        com.brickset.api.ArrayOfSets _getRecentlyUpdatedSets__return = port.getRecentlyUpdatedSets(_getRecentlyUpdatedSets_apiKey, _getRecentlyUpdatedSets_minutesAgo);
        System.out.println("getRecentlyUpdatedSets.result=" + _getRecentlyUpdatedSets__return);


        }
        {
        System.out.println("Invoking getThemes...");
        java.lang.String _getThemes_apiKey = "";
        com.brickset.api.ArrayOfThemes _getThemes__return = port.getThemes(_getThemes_apiKey);
        System.out.println("getThemes.result=" + _getThemes__return);


        }
        {
        System.out.println("Invoking setCollectionQtyOwned...");
        java.lang.String _setCollectionQtyOwned_apiKey = "";
        java.lang.String _setCollectionQtyOwned_userHash = "";
        int _setCollectionQtyOwned_setID = 0;
        int _setCollectionQtyOwned_qtyOwned = 0;
        java.lang.String _setCollectionQtyOwned__return = port.setCollectionQtyOwned(_setCollectionQtyOwned_apiKey, _setCollectionQtyOwned_userHash, _setCollectionQtyOwned_setID, _setCollectionQtyOwned_qtyOwned);
        System.out.println("setCollectionQtyOwned.result=" + _setCollectionQtyOwned__return);


        }
        {
        System.out.println("Invoking getMinifigCollection...");
        java.lang.String _getMinifigCollection_apiKey = "";
        java.lang.String _getMinifigCollection_userHash = "";
        java.lang.String _getMinifigCollection_query = "";
        java.lang.String _getMinifigCollection_owned = "";
        java.lang.String _getMinifigCollection_wanted = "";
        com.brickset.api.ArrayOfMinifigCollection _getMinifigCollection__return = port.getMinifigCollection(_getMinifigCollection_apiKey, _getMinifigCollection_userHash, _getMinifigCollection_query, _getMinifigCollection_owned, _getMinifigCollection_wanted);
        System.out.println("getMinifigCollection.result=" + _getMinifigCollection__return);


        }
        {
        System.out.println("Invoking checkKey...");
        java.lang.String _checkKey_apiKey = "";
        java.lang.String _checkKey__return = port.checkKey(_checkKey_apiKey);
        System.out.println("checkKey.result=" + _checkKey__return);


        }
        {
        System.out.println("Invoking setCollectionDetail...");
        java.lang.String _setCollectionDetail_apiKey = "";
        java.lang.String _setCollectionDetail_userHash = "";
        com.brickset.api.CollectionDetails _setCollectionDetail_detail = null;
        java.lang.String _setCollectionDetail__return = port.setCollectionDetail(_setCollectionDetail_apiKey, _setCollectionDetail_userHash, _setCollectionDetail_detail);
        System.out.println("setCollectionDetail.result=" + _setCollectionDetail__return);


        }
        {
        System.out.println("Invoking getSet...");
        java.lang.String _getSet_apiKey = "";
        java.lang.String _getSet_userHash = "";
        java.lang.String _getSet_setID = "";
        com.brickset.api.ArrayOfSets _getSet__return = port.getSet(_getSet_apiKey, _getSet_userHash, _getSet_setID);
        System.out.println("getSet.result=" + _getSet__return);


        }
        {
        System.out.println("Invoking getCollectionDetailConditions...");
        java.lang.String _getCollectionDetailConditions_apiKey = "";
        java.lang.String _getCollectionDetailConditions_which = "";
        com.brickset.api.ArrayOfConditions _getCollectionDetailConditions__return = port.getCollectionDetailConditions(_getCollectionDetailConditions_apiKey, _getCollectionDetailConditions_which);
        System.out.println("getCollectionDetailConditions.result=" + _getCollectionDetailConditions__return);


        }
        {
        System.out.println("Invoking setCollectionUserNotes...");
        java.lang.String _setCollectionUserNotes_apiKey = "";
        java.lang.String _setCollectionUserNotes_userHash = "";
        int _setCollectionUserNotes_setID = 0;
        java.lang.String _setCollectionUserNotes_notes = "";
        java.lang.String _setCollectionUserNotes__return = port.setCollectionUserNotes(_setCollectionUserNotes_apiKey, _setCollectionUserNotes_userHash, _setCollectionUserNotes_setID, _setCollectionUserNotes_notes);
        System.out.println("setCollectionUserNotes.result=" + _setCollectionUserNotes__return);


        }
        {
        System.out.println("Invoking getYearsForUser...");
        java.lang.String _getYearsForUser_apiKey = "";
        java.lang.String _getYearsForUser_theme = "";
        java.lang.String _getYearsForUser_userHash = "";
        java.lang.String _getYearsForUser_owned = "";
        java.lang.String _getYearsForUser_wanted = "";
        com.brickset.api.ArrayOfYears _getYearsForUser__return = port.getYearsForUser(_getYearsForUser_apiKey, _getYearsForUser_theme, _getYearsForUser_userHash, _getYearsForUser_owned, _getYearsForUser_wanted);
        System.out.println("getYearsForUser.result=" + _getYearsForUser__return);


        }
        {
        System.out.println("Invoking getYears...");
        java.lang.String _getYears_apiKey = "";
        java.lang.String _getYears_theme = "";
        com.brickset.api.ArrayOfYears _getYears__return = port.getYears(_getYears_apiKey, _getYears_theme);
        System.out.println("getYears.result=" + _getYears__return);


        }
        {
        System.out.println("Invoking getSubthemesForUser...");
        java.lang.String _getSubthemesForUser_apiKey = "";
        java.lang.String _getSubthemesForUser_theme = "";
        java.lang.String _getSubthemesForUser_userHash = "";
        java.lang.String _getSubthemesForUser_owned = "";
        java.lang.String _getSubthemesForUser_wanted = "";
        com.brickset.api.ArrayOfSubthemes _getSubthemesForUser__return = port.getSubthemesForUser(_getSubthemesForUser_apiKey, _getSubthemesForUser_theme, _getSubthemesForUser_userHash, _getSubthemesForUser_owned, _getSubthemesForUser_wanted);
        System.out.println("getSubthemesForUser.result=" + _getSubthemesForUser__return);


        }
        {
        System.out.println("Invoking getThemesForUser...");
        java.lang.String _getThemesForUser_apiKey = "";
        java.lang.String _getThemesForUser_userHash = "";
        java.lang.String _getThemesForUser_owned = "";
        java.lang.String _getThemesForUser_wanted = "";
        com.brickset.api.ArrayOfThemes _getThemesForUser__return = port.getThemesForUser(_getThemesForUser_apiKey, _getThemesForUser_userHash, _getThemesForUser_owned, _getThemesForUser_wanted);
        System.out.println("getThemesForUser.result=" + _getThemesForUser__return);


        }
        {
        System.out.println("Invoking getInstructions...");
        java.lang.String _getInstructions_apiKey = "";
        int _getInstructions_setID = 0;
        com.brickset.api.ArrayOfInstructions _getInstructions__return = port.getInstructions(_getInstructions_apiKey, _getInstructions_setID);
        System.out.println("getInstructions.result=" + _getInstructions__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_apiKey = "";
        java.lang.String _login_username = "";
        java.lang.String _login_password = "";
        java.lang.String _login__return = port.login(_login_apiKey, _login_username, _login_password);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking getSets...");
        java.lang.String _getSets_apiKey = "";
        java.lang.String _getSets_userHash = "";
        java.lang.String _getSets_query = "";
        java.lang.String _getSets_theme = "";
        java.lang.String _getSets_subtheme = "";
        java.lang.String _getSets_setNumber = "";
        java.lang.String _getSets_year = "";
        java.lang.String _getSets_owned = "";
        java.lang.String _getSets_wanted = "";
        java.lang.String _getSets_orderBy = "";
        java.lang.String _getSets_pageSize = "";
        java.lang.String _getSets_pageNumber = "";
        java.lang.String _getSets_userName = "";
        com.brickset.api.ArrayOfSets _getSets__return = port.getSets(_getSets_apiKey, _getSets_userHash, _getSets_query, _getSets_theme, _getSets_subtheme, _getSets_setNumber, _getSets_year, _getSets_owned, _getSets_wanted, _getSets_orderBy, _getSets_pageSize, _getSets_pageNumber, _getSets_userName);
        System.out.println("getSets.result=" + _getSets__return);


        }
        {
        System.out.println("Invoking setCollectionOwns...");
        java.lang.String _setCollectionOwns_apiKey = "";
        java.lang.String _setCollectionOwns_userHash = "";
        int _setCollectionOwns_setID = 0;
        int _setCollectionOwns_owned = 0;
        java.lang.String _setCollectionOwns__return = port.setCollectionOwns(_setCollectionOwns_apiKey, _setCollectionOwns_userHash, _setCollectionOwns_setID, _setCollectionOwns_owned);
        System.out.println("setCollectionOwns.result=" + _setCollectionOwns__return);


        }
        {
        System.out.println("Invoking getSubthemes...");
        java.lang.String _getSubthemes_apiKey = "";
        java.lang.String _getSubthemes_theme = "";
        com.brickset.api.ArrayOfSubthemes _getSubthemes__return = port.getSubthemes(_getSubthemes_apiKey, _getSubthemes_theme);
        System.out.println("getSubthemes.result=" + _getSubthemes__return);


        }
        {
        System.out.println("Invoking setMinifigCollection...");
        java.lang.String _setMinifigCollection_apiKey = "";
        java.lang.String _setMinifigCollection_userHash = "";
        java.lang.String _setMinifigCollection_minifigNumber = "";
        int _setMinifigCollection_qtyOwned = 0;
        int _setMinifigCollection_wanted = 0;
        java.lang.String _setMinifigCollection__return = port.setMinifigCollection(_setMinifigCollection_apiKey, _setMinifigCollection_userHash, _setMinifigCollection_minifigNumber, _setMinifigCollection_qtyOwned, _setMinifigCollection_wanted);
        System.out.println("setMinifigCollection.result=" + _setMinifigCollection__return);


        }
        {
        System.out.println("Invoking getAdditionalImages...");
        java.lang.String _getAdditionalImages_apiKey = "";
        int _getAdditionalImages_setID = 0;
        com.brickset.api.ArrayOfAdditionalImages _getAdditionalImages__return = port.getAdditionalImages(_getAdditionalImages_apiKey, _getAdditionalImages_setID);
        System.out.println("getAdditionalImages.result=" + _getAdditionalImages__return);


        }

        System.exit(0);
    }

}
