package com.brickset.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-28T18:10:42.247-04:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://brickset.com/api/", name = "BricksetAPIv2HttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BricksetAPIv2HttpPost {

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public java.lang.String setCollection(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "setID", name = "setID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID,
        @WebParam(partName = "qtyOwned", name = "qtyOwned", targetNamespace = "http://brickset.com/api/")
        java.lang.String qtyOwned,
        @WebParam(partName = "wanted", name = "wanted", targetNamespace = "http://brickset.com/api/")
        java.lang.String wanted
    );

    @WebMethod(operationName = "setCollection_wants")
    @WebResult(name = "string", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public java.lang.String setCollectionWants(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "setID", name = "setID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID,
        @WebParam(partName = "wanted", name = "wanted", targetNamespace = "http://brickset.com/api/")
        java.lang.String wanted
    );

    @WebMethod
    @WebResult(name = "ArrayOfReviews", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfReviews getReviews(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "setID", name = "setID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID
    );

    @WebMethod
    @WebResult(name = "ArrayOfCollectionDetails", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfCollectionDetails getCollectionDetail(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "SetID", name = "SetID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID
    );

    @WebMethod
    @WebResult(name = "ArrayOfSets", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfSets getRecentlyUpdatedSets(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "minutesAgo", name = "minutesAgo", targetNamespace = "http://brickset.com/api/")
        java.lang.String minutesAgo
    );

    @WebMethod
    @WebResult(name = "ArrayOfConditions", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfConditions getCollectionDetailConditions(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "which", name = "which", targetNamespace = "http://brickset.com/api/")
        java.lang.String which
    );

    @WebMethod
    @WebResult(name = "ArrayOfThemes", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfThemes getThemes(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey
    );

    @WebMethod(operationName = "setCollection_userNotes")
    @WebResult(name = "string", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public java.lang.String setCollectionUserNotes(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "setID", name = "setID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID,
        @WebParam(partName = "notes", name = "notes", targetNamespace = "http://brickset.com/api/")
        java.lang.String notes
    );

    @WebMethod(operationName = "setCollection_qtyOwned")
    @WebResult(name = "string", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public java.lang.String setCollectionQtyOwned(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "setID", name = "setID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID,
        @WebParam(partName = "qtyOwned", name = "qtyOwned", targetNamespace = "http://brickset.com/api/")
        java.lang.String qtyOwned
    );

    @WebMethod
    @WebResult(name = "ArrayOfYears", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfYears getYearsForUser(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "theme", name = "theme", targetNamespace = "http://brickset.com/api/")
        java.lang.String theme,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "owned", name = "owned", targetNamespace = "http://brickset.com/api/")
        java.lang.String owned,
        @WebParam(partName = "wanted", name = "wanted", targetNamespace = "http://brickset.com/api/")
        java.lang.String wanted
    );

    @WebMethod
    @WebResult(name = "ArrayOfYears", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfYears getYears(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "theme", name = "theme", targetNamespace = "http://brickset.com/api/")
        java.lang.String theme
    );

    @WebMethod
    @WebResult(name = "ArrayOfSubthemes", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfSubthemes getSubthemesForUser(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "theme", name = "theme", targetNamespace = "http://brickset.com/api/")
        java.lang.String theme,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "owned", name = "owned", targetNamespace = "http://brickset.com/api/")
        java.lang.String owned,
        @WebParam(partName = "wanted", name = "wanted", targetNamespace = "http://brickset.com/api/")
        java.lang.String wanted
    );

    @WebMethod
    @WebResult(name = "ArrayOfThemes", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfThemes getThemesForUser(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "owned", name = "owned", targetNamespace = "http://brickset.com/api/")
        java.lang.String owned,
        @WebParam(partName = "wanted", name = "wanted", targetNamespace = "http://brickset.com/api/")
        java.lang.String wanted
    );

    @WebMethod
    @WebResult(name = "ArrayOfInstructions", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfInstructions getInstructions(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "setID", name = "setID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public java.lang.String login(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "username", name = "username", targetNamespace = "http://brickset.com/api/")
        java.lang.String username,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://brickset.com/api/")
        java.lang.String password
    );

    @WebMethod
    @WebResult(name = "ArrayOfMinifigCollection", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfMinifigCollection getMinifigCollection(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "query", name = "query", targetNamespace = "http://brickset.com/api/")
        java.lang.String query,
        @WebParam(partName = "owned", name = "owned", targetNamespace = "http://brickset.com/api/")
        java.lang.String owned,
        @WebParam(partName = "wanted", name = "wanted", targetNamespace = "http://brickset.com/api/")
        java.lang.String wanted
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public java.lang.String checkKey(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey
    );

    @WebMethod
    @WebResult(name = "ArrayOfSets", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfSets getSets(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "query", name = "query", targetNamespace = "http://brickset.com/api/")
        java.lang.String query,
        @WebParam(partName = "theme", name = "theme", targetNamespace = "http://brickset.com/api/")
        java.lang.String theme,
        @WebParam(partName = "subtheme", name = "subtheme", targetNamespace = "http://brickset.com/api/")
        java.lang.String subtheme,
        @WebParam(partName = "setNumber", name = "setNumber", targetNamespace = "http://brickset.com/api/")
        java.lang.String setNumber,
        @WebParam(partName = "year", name = "year", targetNamespace = "http://brickset.com/api/")
        java.lang.String year,
        @WebParam(partName = "owned", name = "owned", targetNamespace = "http://brickset.com/api/")
        java.lang.String owned,
        @WebParam(partName = "wanted", name = "wanted", targetNamespace = "http://brickset.com/api/")
        java.lang.String wanted,
        @WebParam(partName = "orderBy", name = "orderBy", targetNamespace = "http://brickset.com/api/")
        java.lang.String orderBy,
        @WebParam(partName = "pageSize", name = "pageSize", targetNamespace = "http://brickset.com/api/")
        java.lang.String pageSize,
        @WebParam(partName = "pageNumber", name = "pageNumber", targetNamespace = "http://brickset.com/api/")
        java.lang.String pageNumber,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "http://brickset.com/api/")
        java.lang.String userName
    );

    @WebMethod(operationName = "setCollection_owns")
    @WebResult(name = "string", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public java.lang.String setCollectionOwns(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "setID", name = "setID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID,
        @WebParam(partName = "owned", name = "owned", targetNamespace = "http://brickset.com/api/")
        java.lang.String owned
    );

    @WebMethod
    @WebResult(name = "ArrayOfSubthemes", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfSubthemes getSubthemes(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "theme", name = "theme", targetNamespace = "http://brickset.com/api/")
        java.lang.String theme
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public java.lang.String setMinifigCollection(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "minifigNumber", name = "minifigNumber", targetNamespace = "http://brickset.com/api/")
        java.lang.String minifigNumber,
        @WebParam(partName = "qtyOwned", name = "qtyOwned", targetNamespace = "http://brickset.com/api/")
        java.lang.String qtyOwned,
        @WebParam(partName = "wanted", name = "wanted", targetNamespace = "http://brickset.com/api/")
        java.lang.String wanted
    );

    @WebMethod
    @WebResult(name = "ArrayOfAdditionalImages", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfAdditionalImages getAdditionalImages(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "setID", name = "setID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID
    );

    @WebMethod
    @WebResult(name = "ArrayOfSets", targetNamespace = "http://brickset.com/api/", partName = "Body")
    public ArrayOfSets getSet(
        @WebParam(partName = "apiKey", name = "apiKey", targetNamespace = "http://brickset.com/api/")
        java.lang.String apiKey,
        @WebParam(partName = "userHash", name = "userHash", targetNamespace = "http://brickset.com/api/")
        java.lang.String userHash,
        @WebParam(partName = "SetID", name = "SetID", targetNamespace = "http://brickset.com/api/")
        java.lang.String setID
    );
}
